openapi: 3.0.0
info:
  title: Breeze API
  description: API for authentication and user operations.
  version: "1.0.0"
servers:
  - url: http://localhost:8000/api
    description: Local server
paths:
  /auth/login:
    post:
      summary: User login
      description: Logs in a user and returns an access token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin@admin.com
                password:
                  type: string
                  example: password
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
      tags:
        - Auth
  /auth/register:
    post:
      summary: User registration
      description: Registers a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: user
                email:
                  type: string
                  example: random@example.com
                password:
                  type: string
                  example: password
                password_confirmation:
                  type: string
                  example: password
      responses:
        "201":
          description: User registered successfully
      tags:
        - Auth
  /auth/user:
    get:
      summary: Get user information
      description: Retrieves authenticated user information.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
      tags:
        - Auth
  /auth/logout:
    delete:
      summary: Logout user
      description: Logs out the current user and clears the token.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Logout successful
      tags:
        - Auth
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
